version: "3"
services:
  node:
    build: ./Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app/
    links:
      - mysql
    depends_on:
      - mysql
  mysql:
    image: "mysql/mysql-server"
    ports:
      - "33280:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "rkfaorl453!"
      MYSQL_DATABASE: "Footprint"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "rkfaorl453!"
    volumes:
      - dataonly:/var/lib/mysql
    expose:
      - "33280"
volumes:
  dataonly: {}